services:
  - type: web
    name: rand-real-estate
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build && npm run migrate
    startCommand: node server/production-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FORCE_HTTPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: rand-real-estate-db
          property: connectionString

databases:
  - name: rand-real-estate-db
    databaseName: rand_real_estate
    user: postgres
    plan: free 