services:
  - type: web
    name: RealEstateWebs
    runtime: node
    repo: https://github.com/iam-rekt/RealEstateWebs
    plan: standard
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: node server/production-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: FORCE_HTTPS
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: rand-real-estate-db
          property: connectionString
    region: oregon
    domains:
      - randestate.co
      - www.randestate.co
    autoDeployTrigger: commit

databases:
  - name: rand-real-estate-db
    databaseName: rand_real_estate
    plan: free

version: "1" 